// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtv5Abrym0kS4vABnK4LKXC001qLiFm48',
    appId: '1:434788203531:web:8ff95afb1df89866369b0e',
    messagingSenderId: '434788203531',
    projectId: 'chantier-e7c60',
    authDomain: 'chantier-e7c60.firebaseapp.com',
    storageBucket: 'chantier-e7c60.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF9egtyqSN0in132Lazb_FTzA9XOLtIpk',
    appId: '1:434788203531:android:e7f87f0dbbddd618369b0e',
    messagingSenderId: '434788203531',
    projectId: 'chantier-e7c60',
    storageBucket: 'chantier-e7c60.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7gB8WEpCLTK-zx03hJllEhssdZ3RcMhg',
    appId: '1:434788203531:ios:18b99e642eaf6635369b0e',
    messagingSenderId: '434788203531',
    projectId: 'chantier-e7c60',
    storageBucket: 'chantier-e7c60.appspot.com',
    iosClientId: '434788203531-tgk5eh0jldltsojdri4q4trru4ikmf33.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7gB8WEpCLTK-zx03hJllEhssdZ3RcMhg',
    appId: '1:434788203531:ios:18b99e642eaf6635369b0e',
    messagingSenderId: '434788203531',
    projectId: 'chantier-e7c60',
    storageBucket: 'chantier-e7c60.appspot.com',
    iosClientId: '434788203531-tgk5eh0jldltsojdri4q4trru4ikmf33.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtv5Abrym0kS4vABnK4LKXC001qLiFm48',
    appId: '1:434788203531:web:af884bf00231c548369b0e',
    messagingSenderId: '434788203531',
    projectId: 'chantier-e7c60',
    authDomain: 'chantier-e7c60.firebaseapp.com',
    storageBucket: 'chantier-e7c60.appspot.com',
  );
}
